version: '2'
services:
  ws_soap:
    build: .
    command: java -cp web_SOAP-1.0-SNAPSHOT-jar-with-dependencies.jar Web_SOAP.endpoint.UsersPublisher;
    ports:
    - 80:5005
    links:
    - "web"
    depends_on:
    - web
    networks:
    - nets
  web:
    build: Lab2
    command: python app_new.py
    ports:
    - 5001:5001
    links:
    - "friendservice"
    depends_on:
    - friendservice
    networks:
    - nets
  friendservice:
    build: Lab2
    command: python app.py
    ports:
    - 5000:5000
    networks:
    - nets

networks:
  nets:
